export const states = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
  ];
  export const cartobject = [
    {
      id: 1,
      brand: "MAJIK",
      category: "clothes",
      imageUrl:
        "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-cap.png",
      price: 288,
      title: "Wide Bowknot Hat",
      quantity: 1,
    },
    {
      id: 2,
      brand: "Huetrap",
      category: "clothes",
      imageUrl:
        "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-fit-t-shirt.png",
      price: 395,
      title: "Plain Round Neck T-shirt",
      quantity: 1,
    },
    {
      id: 4,
      brand: "LEVIS",
      category: "clothes",
      imageUrl:
        "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-jacket.png",
      price: 2500,
      title: "Men's Waistcoat",
      quantity: 1,
    },
    {
      id: 3,
      brand: "Scott International",
      category: "clothes",
      imageUrl:
        "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-hoodie.png",
      price: 498,
      title: "Cotton Hoodie",
      quantity: 1,
    },
  ];